//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.04 at 10:19:25 PM CAT 
//


package za.co.xigler.business.bookstore.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the za.co.xigler.business.bookstore.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: za.co.xigler.business.bookstore.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bookstore }
     * 
     */
    public Bookstore createBookstore() {
        return new Bookstore();
    }

    /**
     * Create an instance of {@link Bookstore.Book }
     * 
     */
    public Bookstore.Book createBookstoreBook() {
        return new Bookstore.Book();
    }

    /**
     * Create an instance of {@link Bookstore.Book.Title }
     * 
     */
    public Bookstore.Book.Title createBookstoreBookTitle() {
        return new Bookstore.Book.Title();
    }

    /**
     * Create an instance of {@link Bookstore.Book.Authors }
     * 
     */
    public Bookstore.Book.Authors createBookstoreBookAuthors() {
        return new Bookstore.Book.Authors();
    }

}
